% ------------------------------------------------------------------------------
% Get OceanGliders variable attributes from OG variable name.
%
% SYNTAX :
%  [o_ogVarStruct] = gl_get_og_var_attributes(a_ogVarName)
%
% INPUT PARAMETERS :
%   a_ogVarName : name of the OG variable
%
% OUTPUT PARAMETERS :
%   o_ogVarStruct : OG variable associated attributes
%
% EXAMPLES :
%
% SEE ALSO :
% AUTHOR : Jean-Philippe Rannou (Capgemini) (jean.philippe.rannou@partenaire-exterieur.ifremer.fr)
% ------------------------------------------------------------------------------
% RELEASES :
%   02/06/20255 - RNU - creation
% ------------------------------------------------------------------------------
function [o_ogVarStruct] = gl_get_og_var_attributes(a_ogVarName)

% output parameters initialization
o_ogVarStruct = [];

ogVarName = a_ogVarName;
again = 1;
while (again ~= 0)

   switch (ogVarName)

      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      % COORDINATE VARIABLES

      case 'TIME'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'TIME', ...
            'typeof', 'NC_DOUBLE', ...
            'long_name', 'Time elapsed since 1970-01-01T00:00:00Z', ...
            'calendar', 'gregorian', ...
            'units', 'seconds since 1970-01-01T00:00:00Z', ...
            'FillValue', double(-1), ...
            'valid_min', double(1e9), ...
            'valid_max', double(4e9), ...
            'ancillary_variable', 'TIME_QC', ...
            'interpolation_methodology', '', ...
            'time_vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/TIME/' ...
            );

      case 'LONGITUDE'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'LONGITUDE', ...
            'typeof', 'NC_DOUBLE', ...
            'long_name', 'longitude of each measurement and GPS location', ...
            'standard_name', 'longitude', ...
            'units', 'degrees_east', ...
            'FillValue', double(-9999.9), ...
            'valid_min', double(-180), ...
            'valid_max', double(180), ...
            'ancillary_variable', 'LONGITUDE_QC', ...
            'interpolation_methodology', '', ...
            'longitude_vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/LON/' ...
            );

      case 'LATITUDE'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'LATITUDE', ...
            'typeof', 'NC_DOUBLE', ...
            'long_name', 'Latitude north (WGS84)', ...
            'standard_name', 'latitude', ...
            'units', 'degrees_north', ...
            'FillValue', double(-9999.9), ...
            'valid_min', double(-90), ...
            'valid_max', double(90), ...
            'ancillary_variable', 'LATITUDE_QC', ...
            'interpolation_methodology', '', ...
            'longitude_vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/LAT/' ...
            );

      case 'DEPTH'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'DEPTH', ...
            'typeof', 'NC_DOUBLE', ...
            'long_name', 'Depth below surface of the water body by unknown instrument and correction to zero at sea level using unspecified algorithm.', ...
            'standard_name', 'depth', ...
            'units', 'Metres', ...
            'FillValue', single(-9999.9), ...
            'valid_min', single(0), ...
            'valid_max', single(10000), ...
            'ancillary_variable', 'DEPTH_QC', ...
            'interpolation_methodology', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/DEPTH/' ...
            );

         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
         % GPS VARIABLES

      case 'TIME_GPS'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'TIME_GPS', ...
            'typeof', 'NC_DOUBLE', ...
            'long_name', 'time of each GPS location', ...
            'calendar', 'gregorian', ...
            'units', 'seconds since 1970-01-01T00:00:00Z', ...
            'FillValue', double(-1), ...
            'valid_min', double(1e9), ...
            'valid_max', double(4e9), ...
            'ancillary_variable', 'TIME_GPS_QC' ...
            );

      case 'LONGITUDE_GPS'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'LONGITUDE_GPS', ...
            'typeof', 'NC_DOUBLE', ...
            'long_name', 'longitude of each GPS location', ...
            'standard_name', 'longitude', ...
            'units', 'degrees_east', ...
            'FillValue', double(-9999.9), ...
            'valid_min', double(-180), ...
            'valid_max', double(180), ...
            'ancillary_variable', 'LONGITUDE_GPS_QC' ...
            );

      case 'LATITUDE_GPS'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'LATITUDE_GPS', ...
            'typeof', 'NC_DOUBLE', ...
            'long_name', 'latitude of each GPS location', ...
            'standard_name', 'latitude', ...
            'units', 'degrees_north', ...
            'FillValue', double(-9999.9), ...
            'valid_min', double(-90), ...
            'valid_max', double(90), ...
            'ancillary_variable', 'LATITUDE_GPS_QC' ...
            );

         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
         % PHASE VARIABLES

      case 'PHASE'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'PHASE', ...
            'typeof', 'NC_BYTE', ...
            'long_name', 'behavior of the glider at sea', ...
            'phase_vocabulary', 'https://github.com/OceanGlidersCommunity/OG-format-user-manual/blob/main/vocabularyCollection/phase.md', ...
            'FillValue', int8(0), ...
            'phase_calculation_method', '', ...
            'phase_calculation_method_vocabulary', '', ...
            'ancillary_variable', 'PHASE_QC' ...
            );

         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
         % GEOPHYSICAL PARAMETERS

      case 'BBP412'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'BBP412', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Particle backscattering at 412 nanometers.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/BBP412/', ...
            'FillValue', single(nan), ...
            'units', 'per metre per steradian', ...
            'ancillary_variable', 'BBP412_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'BBP470'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'BBP470', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Particle backscattering at 470 nanometers.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/BBP470/', ...
            'FillValue', single(nan), ...
            'units', 'per metre per steradian', ...
            'ancillary_variable', 'BBP470_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'BBP532'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'BBP532', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Particle backscattering at 532 nanometers.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/BBP532/', ...
            'FillValue', single(nan), ...
            'units', 'per metre per steradian', ...
            'ancillary_variable', 'BBP532_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'BBP650'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'BBP650', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Particle backscattering at 650 nanometers.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/BBP650/', ...
            'FillValue', single(nan), ...
            'units', 'per metre per steradian', ...
            'ancillary_variable', 'BBP650_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'BBP660'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'BBP660', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Particle backscattering at 660 nanometers.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/BBP660/', ...
            'FillValue', single(nan), ...
            'units', 'per metre per steradian', ...
            'ancillary_variable', 'BBP660_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'BBP700'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'BBP700', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Particle backscattering at 700 nanometers.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/BBP700/', ...
            'FillValue', single(nan), ...
            'units', 'per metre per steradian', ...
            'ancillary_variable', 'BBP700_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'BBP715'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'BBP715', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Particle backscattering at 715 nanometers.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/BBP715/', ...
            'FillValue', single(nan), ...
            'units', 'per metre per steradian', ...
            'ancillary_variable', 'BBP715_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'BBP880'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'BBP880', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Particle backscattering at 880 nanometers.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/BBP880/', ...
            'FillValue', single(nan), ...
            'units', 'per metre per steradian', ...
            'ancillary_variable', 'BBP880_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'BETA470'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'BETA470', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Total angle specific volume from backscattering sensor at 470 nanometers.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/BETA470/', ...
            'FillValue', single(nan), ...
            'units', 'Dimensionless', ...
            'ancillary_variable', 'BETA470_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'BETA532'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'BETA532', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Total angle specific volume from backscattering sensor at 532 nanometers.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/BETA532/', ...
            'FillValue', single(nan), ...
            'units', 'Dimensionless', ...
            'ancillary_variable', 'BETA532_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'BETA660'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'BETA660', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Total angle specific volume from backscattering sensor at 660 nanometers.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/BETA660/', ...
            'FillValue', single(nan), ...
            'units', 'Dimensionless', ...
            'ancillary_variable', 'BETA660_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'BETA700'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'BETA700', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Total angle specific volume from backscattering sensor at 700 nanometers.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/BETA700/', ...
            'FillValue', single(nan), ...
            'units', 'Dimensionless', ...
            'ancillary_variable', 'BETA700_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'BETA880'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'BETA880', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Total angle specific volume from backscattering sensor at 880 nanometers.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/BETA880/', ...
            'FillValue', single(nan), ...
            'units', 'Dimensionless', ...
            'ancillary_variable', 'BETA880_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'BPHDOXY'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'BPHDOXY', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Uncalibrated blue excitation light phase shift reported by oxygen sensor.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/BPHDOXY/', ...
            'FillValue', single(nan), ...
            'units', 'Degrees', ...
            'ancillary_variable', 'BPHDOXY_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'C1PHDOXY'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'C1PHDOXY', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Uncalibrated phase shift reported by oxygen sensor.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/C1PHDOXY/', ...
            'FillValue', single(nan), ...
            'units', 'Degrees', ...
            'ancillary_variable', 'C1PHDOXY_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'C2PHDOXY'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'C2PHDOXY', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Uncalibrated phase shift reported by oxygen sensor.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/C2PHDOXY/', ...
            'FillValue', single(nan), ...
            'units', 'Degrees', ...
            'ancillary_variable', 'C2PHDOXY_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'CDOM'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'CDOM', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'The quantity of coloured organic compounds in solution in unit volume of any body of water.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/CDOM/', ...
            'FillValue', single(nan), ...
            'units', 'Parts per billion', ...
            'ancillary_variable', 'CDOM_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'CHLA'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'CHLA', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'In-situ fluorometer with either manufacturer, laboratory or sample calibration applied.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/CHLA/', ...
            'FillValue', single(nan), ...
            'units', 'Milligrams per cubic metre', ...
            'ancillary_variable', 'CHLA_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'CNDC'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'CNDC', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Electrical conductivity of the water body by CTD', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/CNDC/', ...
            'FillValue', single(nan), ...
            'units', 'Siemens per metre', ...
            'ancillary_variable', 'CNDC_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'CNTDOXY'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'CNTDOXY', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'The raw output from a dissolved oxygen sensor such as an SBE43 with output converted from voltage or frequency into counts by an ADC.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/CNTDOXY/', ...
            'FillValue', single(nan), ...
            'units', 'Dimensionless', ...
            'ancillary_variable', 'CNTDOXY_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'DOXY'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'DOXY', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Concentration of dissolved oxygen per unit mass of the water column. Oxygen may be expressed in terms of mass, volume or quantity of substance.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/DOXY/', ...
            'FillValue', single(nan), ...
            'units', 'Micromoles per kilogram', ...
            'ancillary_variable', 'DOXY_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'DPAR'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'DPAR', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Downwelling vector irradiance as energy of electromagnetic radiation (PAR wavelengths) in the water body by cosine-collector radiometer.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/DPAR/', ...
            'FillValue', single(nan), ...
            'units', 'MicroEinsteins per square metre per second', ...
            'ancillary_variable', 'DPAR_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'DPHDOXY'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'DPHDOXY', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'D phase is calculated as a third degree polynomial of (the phase angle measured by blue excitation light minus the phase angle measured by red excitation light).', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/DPHDOXY/', ...
            'FillValue', single(nan), ...
            'units', 'Degrees', ...
            'ancillary_variable', 'DPHDOXY_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'ED380'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'ED380', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'The vertical component of light at 380nm wavelength travelling downwards.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/ED380/', ...
            'FillValue', single(nan), ...
            'units', 'Watts per square metre per nanometre', ...
            'ancillary_variable', 'ED380_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'ED412'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'ED412', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'The vertical component of light at 412nm wavelength travelling downwards.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/ED412/', ...
            'FillValue', single(nan), ...
            'units', 'Watts per square metre per nanometre', ...
            'ancillary_variable', 'ED412_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'ED443'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'ED443', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'The vertical component of light at 443nm wavelength travelling downwards.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/ED443/', ...
            'FillValue', single(nan), ...
            'units', 'Watts per square metre per nanometre', ...
            'ancillary_variable', 'ED443_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'ED490'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'ED490', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'The vertical component of light at 490nm wavelength travelling downwards.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/ED490/', ...
            'FillValue', single(nan), ...
            'units', 'Watts per square metre per nanometre', ...
            'ancillary_variable', 'ED490_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'ED532'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'ED532', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'The vertical component of light at 532nm wavelength travelling downwards.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/ED532/', ...
            'FillValue', single(nan), ...
            'units', 'Watts per square metre per nanometre', ...
            'ancillary_variable', 'ED532_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'ED555'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'ED555', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'The vertical component of light at 555nm wavelength travelling downwards.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/ED555/', ...
            'FillValue', single(nan), ...
            'units', 'Watts per square metre per nanometre', ...
            'ancillary_variable', 'ED555_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'ED665'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'ED665', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'The vertical component of light at 665nm wavelength travelling downwards.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/ED665/', ...
            'FillValue', single(nan), ...
            'units', 'Watts per square metre per nanometre', ...
            'ancillary_variable', 'ED665_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'EDLAM412'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'EDLAM412', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'The raw output expressed in counts from an upward-facing cosine collector radiometer for optical wavelength 412nm.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/EDLAM412/', ...
            'FillValue', single(nan), ...
            'units', 'Dimensionless', ...
            'ancillary_variable', 'EDLAM412_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'EDLAM443'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'EDLAM443', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'The raw output expressed in counts from an upward-facing cosine collector radiometer for optical wavelength 443nm.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/EDLAM443/', ...
            'FillValue', single(nan), ...
            'units', 'Dimensionless', ...
            'ancillary_variable', 'EDLAM443_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'EDLAM490'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'EDLAM490', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'The raw output expressed in counts from an upward-facing cosine collector radiometer for optical wavelength 490nm.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/EDLAM490/', ...
            'FillValue', single(nan), ...
            'units', 'Dimensionless', ...
            'ancillary_variable', 'EDLAM490_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'EDLAM555'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'EDLAM555', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'The raw output expressed in counts from an upward-facing cosine collector radiometer for optical wavelength 555nm.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/EDLAM555/', ...
            'FillValue', single(nan), ...
            'units', 'Dimensionless', ...
            'ancillary_variable', 'EDLAM555_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'FLUOCDOM'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'FLUOCDOM', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'The amount of violet to low ultra-violet radiation generated in the water column in response to high ultra-violet radiation transmission expressed relative to an unspecified baseline using fluorometer designed to detect CDOM, crude oil or UV-fluorescent dyes.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/FLUOCDOM/', ...
            'FillValue', single(nan), ...
            'units', 'Dimensionless', ...
            'ancillary_variable', 'FLUOCDOM_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'FLUOCHLA'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'FLUOCHLA', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Raw fluorescence signal (count) from chlorophyll-a fluorometer.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/FLUOCHLA/', ...
            'FillValue', single(nan), ...
            'units', 'Dimensionless', ...
            'ancillary_variable', 'FLUOCHLA_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'FREQDOXY'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'FREQDOXY', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'The raw output from a dissolved oxygen sensor such as an SBE43 with output as a frequency related to DO concentration.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/FREQDOXY/', ...
            'FillValue', single(nan), ...
            'units', 'Hertz', ...
            'ancillary_variable', 'FREQDOXY_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'HEADING'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'HEADING', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', '', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/HEADING/', ...
            'FillValue', single(nan), ...
            'units', 'Degrees', ...
            'ancillary_variable', 'HEADING_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'LCNTDOXY'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'LCNTDOXY', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Number of times oxygen sensor flashing to measure oxygen.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/LCNTDOXY/', ...
            'FillValue', single(nan), ...
            'units', 'Dimensionless', ...
            'ancillary_variable', 'LCNTDOXY_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'MLPLDOXY'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'MLPLDOXY', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Concentration of dissolved oxygen per unit volume of the water column. Oxygen may be expressed in terms of mass, volume or quantity of substance.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/MLPLDOXY/', ...
            'FillValue', single(nan), ...
            'units', 'Millilitres per litre', ...
            'ancillary_variable', 'MLPLDOXY_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'MOLDOXY'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'MOLDOXY', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Water body dissolved oxygen concentration expressed at zero rather than in-situ salinity. This is NOT an environment state variable.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/MOLDOXY/', ...
            'FillValue', single(nan), ...
            'units', 'Millimoles per litre', ...
            'ancillary_variable', 'MOLDOXY_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'NBSAMP'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'NBSAMP', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Number of values included in the determination of a statistic such as an average.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/NBSAMP/', ...
            'FillValue', single(nan), ...
            'units', 'Dimensionless', ...
            'ancillary_variable', 'NBSAMP_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'NCNTTUR1'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'NCNTTUR1', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Turbidity signal from side scattering sensor.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/NCNTTUR1/', ...
            'FillValue', single(nan), ...
            'units', 'Dimensionless', ...
            'ancillary_variable', 'NCNTTUR1_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'PHDEDOXY'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'PHDEDOXY', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Phase delay reported by oxygen sensor.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/PHDEDOXY/', ...
            'FillValue', single(nan), ...
            'units', 'Microseconds', ...
            'ancillary_variable', 'PHDEDOXY_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'PITCH'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'PITCH', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', '', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/PITCH/', ...
            'FillValue', single(nan), ...
            'units', 'Degrees', ...
            'ancillary_variable', 'PITCH_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'PPOXDOXY'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'PPOXDOXY', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', '', ...
            'standard_name', 'The partial pressure of oxygen in air in equilibrium with a water sample.', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/PPOXDOXY/', ...
            'FillValue', single(nan), ...
            'units', 'Millibars', ...
            'ancillary_variable', 'PPOXDOXY_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'PSAL'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'PSAL', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Practical salinity of the water body by CTD and computation using UNESCO 1983 algorithm', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/PSAL/', ...
            'FillValue', single(nan), ...
            'units', 'Dimensionless', ...
            'ancillary_variable', 'PSAL_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'RAWDPAR'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'RAWDPAR', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'The raw output expressed in counts from an upward-facing cosine collector radiometer measuring the integrated light over PAR wavelengths.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/RAWDPAR/', ...
            'FillValue', single(nan), ...
            'units', 'Dimensionless', ...
            'ancillary_variable', 'RAWDPAR_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'ROLL'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'ROLL', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', '', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/ROLL/', ...
            'FillValue', single(nan), ...
            'units', 'Degrees', ...
            'ancillary_variable', 'ROLL_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'RPHDOXY'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'RPHDOXY', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Uncalibrated red excitation light phase shift reported by oxygen sensor.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/RPHDOXY/', ...
            'FillValue', single(nan), ...
            'units', 'Degrees', ...
            'ancillary_variable', 'RPHDOXY_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'TCNTDOXY'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'TCNTDOXY', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Count which is expressive of uncalibrated temperature value reported by oxygen sensor.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/TCNTDOXY/', ...
            'FillValue', single(nan), ...
            'units', 'Dimensionless', ...
            'ancillary_variable', 'TCNTDOXY_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'TCPUCHLA'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'TCPUCHLA', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'The raw analogue-to-digital converter output from a temperature sensor mounted on a CPU that is a component part of a backscattering meter and/or fluorometer.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/TCPUCHLA/', ...
            'FillValue', single(nan), ...
            'units', 'Dimensionless', ...
            'ancillary_variable', 'TCPUCHLA_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'TEMP'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'TEMP', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Temperature of the water body by CTD or STD', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/TEMP/', ...
            'FillValue', single(nan), ...
            'units', 'Degrees Celsius', ...
            'ancillary_variable', 'TEMP_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'TEMP_CNDC'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'TEMP_CNDC', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Internal temperature (degC) of the conductivity cell.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/TEMP_CNDC/', ...
            'FillValue', single(nan), ...
            'units', 'Degrees Celsius', ...
            'ancillary_variable', 'TEMP_CNDC_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'TEMPDOXY'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'TEMPDOXY', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Temperature of oxygen determination by optode.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/TEMPDOXY/', ...
            'FillValue', single(nan), ...
            'units', 'Degrees Celsius', ...
            'ancillary_variable', 'TEMPDOXY_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'TPHDOXY'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'TPHDOXY', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Uncalibrated (temperature compensated) phase shift reported by oxygen sensor.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/TPHDOXY/', ...
            'FillValue', single(nan), ...
            'units', 'Degrees', ...
            'ancillary_variable', 'TPHDOXY_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'TURB'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'TURB', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Estimate of suspended sediment concentration based on the proportion of a light transmission in the water column that is reflected back to a co-located receiver.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/TURB/', ...
            'FillValue', single(nan), ...
            'units', '', ...
            'ancillary_variable', 'TURB_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'VLTDOXY'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'VLTDOXY', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'The raw output from a dissolved oxygen sensor such as an SBE43 with output as a voltage related to DO concentration.', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/VLTDOXY/', ...
            'FillValue', single(nan), ...
            'units', 'Volts', ...
            'ancillary_variable', 'VLTDOXY_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'WCUR_X'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'WCUR_X', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Eastward current velocity in the water body', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/WCUR_X/', ...
            'FillValue', single(nan), ...
            'units', 'Centimetres per second', ...
            'ancillary_variable', 'WCUR_X_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      case 'WCUR_Y'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'WCUR_Y', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Northward current velocity in the water body', ...
            'standard_name', '', ...
            'vocabulary', 'https://vocab.nerc.ac.uk/collection/OG1/current/WCUR_Y/', ...
            'FillValue', single(nan), ...
            'units', 'Centimetres per second', ...
            'ancillary_variable', 'WCUR_Y_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

         % TEMPORARY because we cannot store current associated depth to CTD
         % DEPTH measurement
      case 'EGO_WCUR_Z'
         o_ogVarStruct = struct( ...
            'og_variable_name', 'EGO_WCUR_Z', ...
            'typeof', 'NC_FLOAT', ...
            'long_name', 'Associated depth of current velocity in the water body', ...
            'standard_name', '', ...
            'vocabulary', '', ...
            'FillValue', single(nan), ...
            'units', 'Metres', ...
            'ancillary_variable', 'EGO_WCUR_Z_QC', ...
            'coordinates', 'TIME, LONGITUDE, LATITUDE, DEPTH', ...
            'sensor', '' ...
            );

      otherwise
         if (again == 1)
            if (isletter(a_ogVarName(end-1)) && ~isletter(a_ogVarName(end)))
               ogVarName = a_ogVarName(1:end-1);
               again = 2;
            elseif ((a_ogVarName(end-1) == '_') && ~isletter(a_ogVarName(end)))
               ogVarName = a_ogVarName(1:end-2);
               again = 3;
            else
               fprintf('WARNING: OceanGliders variable attributes no yet defined for OceanGliders variable %s\n', a_ogVarName);
               again = 0;
            end
         else
            fprintf('WARNING: OceanGliders variable attributes no yet defined for OceanGliders variable %s\n', a_ogVarName);
            again = 0;
         end
   end
   if (~isempty(o_ogVarStruct))
      if ((again == 2) || (again == 3))
         o_ogVarStruct.og_variable_name = a_ogVarName;
         o_ogVarStruct.ancillary_variable = [a_ogVarName '_QC'];
      end
      again = 0;
   end
end

return
